# Generated by Django 2.2.16 on 2023-05-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genretitle',
            options={'verbose_name': 'Title genres', 'verbose_name_plural': 'Title genres'},
        ),
        migrations.RemoveConstraint(
            model_name='genretitle',
            name='unique title genre constraint',
        ),
        migrations.AddConstraint(
            model_name='genretitle',
            constraint=models.UniqueConstraint(fields=('title', 'genre'), name='unique title-genre constraint'),
        ),
    ]
