# Generated by Django 2.2.16 on 2023-05-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230519_1902'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique review constaint',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique author-review constaint'),
        ),
    ]
